name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

env: 
  AZURE_WEB_APP_NAME: todowebappapi
  AZURE_WEB_APP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 #checkout your code for processing

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./todolistappapi

      - name: Build
        run: dotnet build ./todolistappapi --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./todolistappapi --configuration Release --no-build --output '${{env.AZURE_WEB_APP_PACKAGE_PATH}}'

      - name: Deployment
        uses: actions/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEB_APP_NAME}}
          publish-profile: ${{secrets.AZURE_API_SECRETS}}
          package: "${{env.AZURE_WEB_APP_PACKAGE_PATH}}"
          
      
      
